steps:
  - label: ':radioactive_sign: :darwin:'
    command: bazelisk clean --expunge
    parallelism: 4
    agents:
      - PLATFORM: macos_x86_64

  - label: ':radioactive_sign: :linux:'
    command: bazelisk clean --expunge
    parallelism: 2
    agents:
      PLATFORM: linux_x86_64

  - label: ':radioactive_sign: :windows:'
    command: bazelisk clean --expunge
    parallelism: 2
    agents:
      PLATFORM: windows_x86_64
