env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

steps:
# build phase

{{#variants}}
  - label: ':hammer_and_wrench: {{emoji}}'
    command: '{{python}} ci/buildkite.py build {{name}}'
    key: '{{name}}'
    agents:
      PLATFORM: '{{name}}'
    artifact_paths:
      {{#artifacts}}
      - "tmp/build/**/*"
      {{/artifacts}}
      - "bazel-testlogs/**/test.log"
{{/variants}}


